седона - 1 часть
htmlacademy-htmlcss/1657873-sedona-34 pull request #2
Opened 2022-05-25 02:26 UTC by ah-keti

2022-05-27 12:55 UTC, mikhin requested changes
Привет! Вполне неплохо, молодец!

Проверь, пожалуйста, еще раз оба документа на валидацию тут — https://validator.w3.org/nu/#textarea.

2022-05-27 12:55 UTC, mikhin commented on catalog.html
> +        <li class="navigation-item">
Лучше бы поправить форматирование — добавить отступы вложенным элементам.

2022-05-27 12:55 UTC, mikhin commented on catalog.html
> +        <ul class="navigation-list navigation-user">
Я считаю, что вот это второе меню — не является частью основной навигации, поэтому я бы посоветовал вынести его из `nav`.

2022-05-27 12:55 UTC, mikhin commented on catalog.html
> +            <a class="navigation-link" href="#">Хочу сюда!</a>
Лучше бы перенести закрывающий тег на следующую строку.

2022-05-27 12:55 UTC, mikhin commented on catalog.html
> +      <main class="main-inner">
`main-inner` > `inner-page`, `catalog-page`

не очень понятно что такое `главная внутренняя`

2022-05-27 12:55 UTC, mikhin commented on catalog.html
> +              <a class="breadcrumbs-link">Гостиницы</a>
Тут скорее должны хотеть `span`, а не `a`, т.к. на странице не должно быть ссылок на саму себя. Это не жесткое требование, но например рекомендация поисковых систем.

2022-05-27 12:55 UTC, mikhin commented on catalog.html
> +          <legend>Стоимость, ₽:</legend>
Нужно добавить текстовые поля и разметку кастомного слайдера с двумя ползунками.

2022-05-27 12:55 UTC, mikhin commented on catalog.html
> +    <select class="select-control" aria-label="Сортировка">
Тут кажется нужно поправить форматирование всего документа в целом — необходимо, чтобы отступы отображали вложенность элементов. Так намного проще читать код.

Редакторы кода должны это уметь делать автоматически, по одному нажатию хоткея. Погуглишь, как это делается в твоем редакторе?

2022-05-27 12:55 UTC, mikhin commented on catalog.html
> +      <option value="popular">Сначала популярное</option>
Тут что-то странное — `option` должны быть вложены в `select`.

2022-05-27 12:55 UTC, mikhin commented on catalog.html
> +          <li class="hotel-card">
Нужно поправить форматирование.

2022-05-27 12:55 UTC, mikhin commented on catalog.html
> +          </il>
Опечатка

2022-05-27 12:55 UTC, mikhin commented on catalog.html
> +              <p>Гостиница</p>
Не уверен, что слово "Гостиница" должно быть ссылкой.

2022-05-27 12:55 UTC, mikhin commented on catalog.html
> +            <a class="hotel-card-button button" href="#">в избранное</a>
С большой буквы лучше бы написать — по правилам оформления текстов в русском языке.

2022-05-27 12:55 UTC, mikhin commented on catalog.html
> +                <span class="visually-hidden">...</span>
Не очень понятно зачем прятать троеточие =)

2022-05-27 12:55 UTC, mikhin commented on catalog.html
> +          <li class="pagination-item">
Кажется, этот селект уже не пункт списка пагинации.

2022-05-27 12:55 UTC, mikhin commented on catalog.html
> +      <section class="newsletter">
Нужно поправить форматирование всей секции.

2022-05-27 12:55 UTC, mikhin commented on catalog.html
> +
Лишние пустые строки.

2022-05-27 12:55 UTC, mikhin commented on catalog.html
> +  </body>
Лишние теги.

2022-05-27 12:55 UTC, mikhin commented on index.html
> +          <li class="advantages-item">
Кажется, это уже не пункт меню преимуществ.

2022-05-27 12:55 UTC, mikhin commented on index.html
>    </body>
Лишние теги.

2022-05-27 12:55 UTC, mikhin commented on index.html
> +          <section class="newsletter">
Это сейчас все еще в верхнем списке `ul` находится. Нужно еще раз проверить вложенность элементов во всем документе.

2022-06-01 09:41 UTC, mikhin requested changes

2022-06-01 09:41 UTC, mikhin commented on index.html
>    <body>
@ah-keti , для главной страницы все еще есть ошибки валидации. Давай их исправим сразу?

https://validator.w3.org/nu/#textarea

2022-06-01 09:41 UTC, mikhin commented on catalog.html
> +<!DOCTYPE html>
Для каталога тоже над проверить валидацию.

2022-06-01 09:41 UTC, mikhin commented on catalog.html
> +        <nav class="navigattion">
Опечатка

2022-06-01 09:41 UTC, mikhin commented on catalog.html
> +        <li class="navigation-item">
Форматирование все таки лучше поправить.

2022-06-01 09:41 UTC, mikhin commented on catalog.html
> +      <img alt="sedona-mountains" src="img/jpg/сatalog.jpg" width="1199.53" height="393">
Дробные значения в 99% случаев не нужны — браузеру придется потратить больше ресурсов на отрисовку.

2022-06-01 09:41 UTC, mikhin commented on catalog.html
> +            <a class="bredcrumbs-link">Гостиницы</a>
Опечатка в слове `breAdcrumbs`

2022-06-01 09:41 UTC, mikhin commented on catalog.html
> +        <a class="currant-page pagination-link">1</a>
опечатка в слове `current`

2022-06-01 18:01 UTC, ah-keti commented on catalog.html
> +<!DOCTYPE html>
готово

2022-06-01 18:02 UTC, ah-keti commented on catalog.html
> +        <nav class="navigattion">
исправила

2022-06-01 18:02 UTC, ah-keti commented on catalog.html
> +            <a class="bredcrumbs-link">Гостиницы</a>
готово

2022-06-02 20:36 UTC, merged