добавила графику для всех страниц
htmlacademy-htmlcss/1657873-sedona-34 pull request #3
Opened 2022-06-06 19:57 UTC by ah-keti

оптимизация картинок

2022-06-16 21:31 UTC, mikhin requested changes
Неплохо! Очень даже =)

Нет смысла делить изображения по типу файла, в этом нет никакой пользы. Бывает, что можно сложить иконки в отдельную папку `icons`, а фотки в `photos`, но тут уже хозяин-барин. Сейчас лучше просто сложить все картинки в одну папку.

Предупреждаю сразу, что скорее всего после всех этих исправлений пойдем на второй круг исправлений, потому что хочется поправить все недочеты и сразу сделать классно, а в один присест можно устать исправлять, поэтому предлагаю правки разделить на две части.

2022-06-16 21:31 UTC, mikhin commented on catalog.html
> +              <img alt="search"src="images/svg/icon-search.svg" width="18" height="18">
Нужен пробел перед `src`.

2022-06-16 21:31 UTC, mikhin commented on catalog.html
> +        <header class="inner-header">
Нужно добавить форматирование вложенных отступов, т.к. `header` лежит внутри `<div class="filter">`.

2022-06-16 21:31 UTC, mikhin commented on catalog.html
> +            <img alt="filter-grid" src="images/svg/icon-table.svg" width="16" height="14">
`alt` это не какой-то технический атрибут, это буквально то, что будет озвучено пользователем специальным голосовым помощником. Поэтому тут надо писать какой-то осмысленный текст всегда, который поможет пользователю.

2022-06-16 21:31 UTC, mikhin commented on catalog.html
> +              <img alt="search"src="images/svg/icon-search.svg" width="18" height="18">
А точно эта картинка нужна тут, в HTML, а не в CSS?

В HTML нужно вставлять только контентные изображения, а не декоративные. Если не очень понятна разница, предлагаю обсудить в личке или на созвоне.

2022-06-16 21:31 UTC, mikhin commented on catalog.html
> +          <div class="hotel-page">
Нужно поправить форматирование текста.

2022-06-16 21:31 UTC, mikhin commented on index.html
> +          <div class="first-image"></div>
Непонятно зачем нужен пустой див.

2022-06-16 21:31 UTC, mikhin commented on styles/styles.css
> +  }
Закрывающая скобка должна быть на том же уровне, на котором открывающая строка.

Еще нужен отступ в пустую строку между всеми селекторами CSS.

2022-06-16 21:31 UTC, mikhin commented on styles/styles.css
> +  }
Нужно поправить форматирование всего CSS, чтобы было все аккуратно и красиво =)

2022-06-16 21:31 UTC, mikhin commented on styles/styles.css
> +  font-family: 'PT Sans';
Всегда нужно указывать запасные шрифты и семейства.

2022-06-16 21:31 UTC, mikhin commented on styles/styles.css
> +  font-family: 'PT Sans', sans-serif;
Лучше указывать шрифтовое семейство не на каждом элементе, а на каком-то самом верхнеуровневом элементе.

2022-06-16 21:31 UTC, mikhin commented on styles/styles.css
> +
Пустая строка лишняя.

2022-06-16 21:31 UTC, mikhin commented on styles/styles.css
> +}
Добавить пустую строку.

2022-06-16 21:31 UTC, mikhin commented on styles/styles.css
> +  left: 160px;
`left` используется только если `position: absolute`, `position: relative`, и т.д.

2022-06-16 21:31 UTC, mikhin commented on styles/styles.css
> +.inner-header-title{
Перед открывающей скобкой нужен пробел.

2022-06-16 21:31 UTC, mikhin commented on styles/styles.css
> +  align-items: center;
`align-items` используется только если установили `display: flex;` или `display: grid`, а тут такого нет.

2022-06-16 21:31 UTC, mikhin commented on styles/styles.css
> +  color: #FFFFFF;
лучше написать маленькими буквами значение цвета

2022-06-16 21:31 UTC, mikhin commented on styles/styles.css
> +  height: 384px;
Всегда лучше сначала постараться указать padding, для того чтобы раскладка была более гибкой.

Если не выходит добиться соответствия макету, тогда да, лучше указывать высоту.

2022-06-16 21:31 UTC, mikhin commented on styles/styles.css
> +  border: 0;
Для кнопок вообще лучше убрать `border`, т.к. в разных браузерах кнопки рисуются по разному. И выставить какой-то `background-color` или сделать его `transparent`.

2022-06-16 21:31 UTC, mikhin commented on styles/styles.css
> +  font-family: "PT Sans Narrow", sans-serif;
Такой шрифт не подключен.

2022-06-25 04:11 UTC, ah-keti commented on styles/styles.css
> +  }
поправила

2022-06-25 04:12 UTC, ah-keti commented on styles/styles.css
> +  font-family: "PT Sans Narrow", sans-serif;
поменяла

2022-06-25 04:12 UTC, ah-keti commented on styles/styles.css
> +  }
готово

2022-08-09 16:42 UTC, closed without merging